Update semantic-versioning-1.yaml

diff --git a/.github/workflows/semantic-versioning-1.yaml b/.github/workflows/semantic-versioning-1.yaml
--- a/.github/workflows/semantic-versioning-1.yaml
+++ b/.github/workflows/semantic-versioning-1.yaml
@@ -53,36 +53,39 @@ jobs:
 
       - name: Calculate new version
         id: calc_version
+        env:
+          IS_MAIN_BRANCH: ${{ github.ref == 'refs/heads/main' }}
+          IS_PR_MERGED_TO_MAIN: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'main' }}
         run: |
-          VERSION=$(tail -n 1 ${{ inputs.version_file_path }})
-          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-          echo "Error: Invalid version format - $VERSION"
-          exit 1
-          fi
+         VERSION=$(tail -n 1 ${{ inputs.version_file_path }})
+         if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+         echo "Error: Invalid version format - $VERSION"
+         exit 1
+         fi
 
-          IFS='.' read -ra ADDR <<< "$VERSION"
-          # Determine if it's a push to main or a merged PR into main
-          if [[ "${{ github.ref }}" == 'refs/heads/main' || ( "${{ github.event_name }}" == 'pull_request' && ${{ github.event.pull_request.merged }} && "${{ github.event.pull_request.base.ref }}" == 'main' ) ]]; then
-          if ${{ inputs.major }}; then
-           ADDR[0]=$((ADDR[0]+1))
+         IFS='.' read -ra ADDR <<< "$VERSION"
+         if [[ "$IS_MAIN_BRANCH" == "true" || "$IS_PR_MERGED_TO_MAIN" == "true" ]]; then
+         if ${{ inputs.major }}; then
+          ADDR[0]=$((ADDR[0]+1))
            ADDR[1]=0
            ADDR[2]=0
-          elif ${{ inputs.minor }}; then
+         elif ${{ inputs.minor }}; then
            ADDR[1]=$((ADDR[1]+1))
            ADDR[2]=0
           elif ${{ inputs.patch }}; then
-           ADDR[2]=$((ADDR[2]+1))
+          ADDR[2]=$((ADDR[2]+1))
+         fi
+         NEW_VERSION="${ADDR[0]}.${ADDR[1]}.${ADDR[2]}"
+         echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
+         echo "# <MAJOR>.<MINOR>.<PATCH>" > ${{ inputs.version_file_path }}
+         echo "$NEW_VERSION" >> ${{ inputs.version_file_path }}
+         else
+           NEW_VERSION=$VERSION
           fi
-          NEW_VERSION="${ADDR[0]}.${ADDR[1]}.${ADDR[2]}"
-          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
-          echo "# <MAJOR>.<MINOR>.<PATCH>" > ${{ inputs.version_file_path }}
-          echo "$NEW_VERSION" >> ${{ inputs.version_file_path }}
-          else
-          NEW_VERSION=$VERSION
-          fi
-          echo "version=$NEW_VERSION" >> $GITHUB_ENV
-          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
-          shell: bash
+             echo "version=$NEW_VERSION" >> $GITHUB_ENV
+             echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
+         shell: bash
+
       - name: Commit new version
         if: env.NEW_VERSION && (github.ref == 'refs/heads/main' || github.event.pull_request.merged)
         run: |
