Update semantic-versioning-1.yaml

diff --git a/.github/workflows/semantic-versioning-1.yaml b/.github/workflows/semantic-versioning-1.yaml
--- a/.github/workflows/semantic-versioning-1.yaml
+++ b/.github/workflows/semantic-versioning-1.yaml
@@ -1,68 +1,91 @@
-name: Version Management
+name: Semantic Versioning
 
 on:
   workflow_call:
     inputs:
-      increment_type:
-        description: 'Type of version increment (major, minor, patch) or "none" to use current version'
-        required: true
-        type: string
+      major:
+        required: false
+        type: boolean
+        default: false
+      minor:
+        required: false
+        type: boolean
+        default: false
+      patch:
+        required: false
+        type: boolean
       version_file_path:
-        description: 'Path to the version file'
         required: true
         type: string
     outputs:
       new_version:
-        description: "The new or current version number."
-        value: ${{ jobs.update_version.outputs.new_version }}
+        description: "The newly calculated semantic version"
+        value: ${{ jobs.versioning.outputs.new_version }}
+
+permissions:
+  contents: write  # This allows the workflow to push changes
 
 jobs:
-  update_version:
+  versioning:
     runs-on: ubuntu-latest
     outputs:
-      new_version: ${{ steps.set_output.outputs.version }}
+      new_version: ${{ steps.calc_version.outputs.version }}
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-      
-      - name: Read current version
-        run: |
-          echo "current_version=$(cat ${{ inputs.version_file_path }})" >> $GITHUB_ENV
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-      - name: Determine increment need based on branch and input
-        id: set_output
+      - name: Get last committer's email
+        id: get-email
         run: |
-          if [[ "${{ github.ref }}" == 'refs/heads/main' ]] && [[ "${{ inputs.increment_type }}" != 'none' ]]; then
-            IFS='.' read -ra VER <<< "$current_version"
-            MAJOR=${VER[0]}
-            MINOR=${VER[1]}
-            PATCH=${VER[2]}
-            
-            case "${{ inputs.increment_type }}" in
-              major)
-                NEW_VERSION=$(($MAJOR + 1)).0.0
-                ;;
-              minor)
-                NEW_VERSION=$MAJOR.$(($MINOR + 1)).0
-                ;;
-              patch)
-                NEW_VERSION=$MAJOR.$MINOR.$(($PATCH + 1))
-                ;;
-            esac
-            echo "version=$NEW_VERSION" >> $GITHUB_ENV
-            echo "${NEW_VERSION}" > ${{ inputs.version_file_path }}
-            echo "version=${NEW_VERSION}" >> $GITHUB_STEP_SUMMARY
-            echo "version=${NEW_VERSION}" > $GITHUB_ENV
-          else
-            echo "version=$current_version" >> $GITHUB_ENV
+          EMAIL=$(git log -1 --pretty=format:'%ae')
+          echo "Last committer's email: $EMAIL"
+          echo "COMMITTER_EMAIL=$EMAIL" >> $GITHUB_ENV
+          
+      # git configuration
+      - name: Configure Git
+        run: |
+          # git config --global user.email "${{ env.COMMITTER_EMAIL }}"
+          git config --global user.name "${{ github.actor }}"
+
+      - name: Pull latest changes
+        run: git pull origin ${{ github.head_ref }} --rebase
+
+
+      - name: Calculate new version
+        id: calc_version
+        run: |
+          VERSION=$(tail -n 1 ${{ inputs.version_file_path }})
+          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Invalid version format - $VERSION"
+            exit 1
           fi
+
+          IFS='.' read -ra ADDR <<< "$VERSION"
+          if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
+            if ${{ inputs.major }}; then
+              ADDR[0]=$((ADDR[0]+1))
+              ADDR[1]=0
+              ADDR[2]=0
+            elif ${{ inputs.minor }}; then
+              ADDR[1]=$((ADDR[1]+1))
+              ADDR[2]=0
+            elif ${{ inputs.patch }}; then
+              ADDR[2]=$((ADDR[2]+1))
+            fi
+            NEW_VERSION="${ADDR[0]}.${ADDR[1]}.${ADDR[2]}"
+            echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
+            echo "# <MAJOR>.<MINOR>.<PATCH>" > ${{ inputs.version_file_path }}
+            echo "$NEW_VERSION" >> ${{ inputs.version_file_path }}
+          else
+            NEW_VERSION=$VERSION
+          fi
+          echo "version=$NEW_VERSION" >> $GITHUB_ENV
+          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
         shell: bash
 
-      - name: Commit and push updated version file
-        if: env.version && github.ref == 'refs/heads/main'
+      - name: Commit new version
+        if: github.ref == 'refs/heads/main' && env.NEW_VERSION
         run: |
-          git config --global user.name 'GitHub Actions'
-          git config --global user.email 'actions@github.com'
           git add ${{ inputs.version_file_path }}
-          git commit -m "chore: update version to ${{ env.version }}"
-          git push
+          git commit -m "Update version to ${{ steps.calc_version.outputs.version }}"
+          git push origin ${{ github.head_ref }}
